### ISSUE TITLE
deps: bump uuid from 10.0.0 to 11.1.0, or use something else for uuid

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2968]
## TODO 
- Options to try: 
  1. Use https://www.npmjs.com/package/react-native-uuid instead of uuid?
  2. Figure out what's going on with uuid (see details)
- Update client-shared to the latest uuid, and update mobile-client's dependency on it

## Details
See history on https://github.com/techmatters/terraso-mobile-client/pull/2535 

When I updated mobile-client to 11.1.0, the test run passed, but the app crashed on Android after logging in. The error was: `TypeError: 0, crypto_1.randomFillSync is not a function (it is undefined), js engine: hermes` 
This was in our file mapSearchService.ts, in initSession, in the call to uuidv4.

So I'm taking mobile-client back to 10.0.0 and opening a new task for this.

Investigation: 
- One hypothesis is that when updated to 11.1.0, the uuid file containing the code containing `crypto_1.randomFillSync` is node_modules/uuid/dist/cjs/rng.js. But there is also a node_modules/uuid/dist/esm/rng.js. Our package-lock.json with 11.1.0 specifies
  ```
        "bin": {
          "uuid": "dist/esm/bin/uuid"
        }
  ```
  Seems like some (non-ECMAScript) things are not supported by hermes for React Native, but haven't fully followed this thread: https://github.com/facebook/hermes/discussions/1072 
  I wonder if something is being configured weirdly or determined incorrectly between CommonJS and ECMAScript? Or just if uuid isn't meant to support

- I tried replacing calls to uuid’s uuidv4() with expo-crypto’s randomUUID() – whose docs say it “returns a unique identifier based on the V4 UUID spec”, but it kept returning undefined.
- There may be other random uuid generator libraries we could use instead on mobile-client. Perhaps we'd prefer react-native-uuid?
